### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sunl888** [techa03/goodsKill#106]
error info
![image](https://user-images.githubusercontent.com/9254545/121470277-8e336900-c9f0-11eb-9809-aaacd097281a.png)

**Comment by techa03** [comment]
> error info
> ![image](https://user-images.githubusercontent.com/9254545/121470277-8e336900-c9f0-11eb-9809-aaacd097281a.png)

是用的openJDK11编译的吗？我本地用的阿里云仓库构建没问题的

**Comment by sunl888** [comment]
> > error info
> > ![image](https://user-images.githubusercontent.com/9254545/121470277-8e336900-c9f0-11eb-9809-aaacd097281a.png)
> 
> 是用的openJDK11编译的吗？我本地用的阿里云仓库构建没问题的

compile with jdk8 ^_^
