### ISSUE TITLE
idea部署，web前端访问404错误

### ISSUE THREAD

**Issue by chenyuming98** [techa03/goodsKill#108]
看了说明文档，解决办法说设置工程启动类的目录，idea...怎么设置启动类目录啊

**Comment by techa03** [comment]
> 看了说明文档，解决办法说设置工程启动类的目录，idea...怎么设置启动类目录啊

![image](https://user-images.githubusercontent.com/16450027/122882870-32150100-d36f-11eb-9126-5d406b71f0e4.png)
