### ISSUE TITLE
秒杀场景八，Redis获取商品及扣库存不是原子操作

### ISSUE THREAD

**Issue by JC0626** [techa03/goodsKill#134]
在秒杀场景八中，通过redis获取秒杀商品和库存扣除操作不是原子操作，在高并发下是否存在问题？
以及MQ失败（发送失败，或者处理失败，网络抖动），如何处理？

**Comment by techa03** [comment]
目前没有考虑失败的情况，后面会完善一下。比如加上redis事务回滚，以及保证消息投递可靠性

**Comment by techa03** [comment]
各位有兴趣的也欢迎提个pr
