### ISSUE TITLE
可以给下慕课的地址吗

### ISSUE THREAD

**Issue by mountain-shui** [techa03/goodsKill#156]
可以给下慕课的地址吗

**Comment by techa03** [comment]
> 可以给下慕课的地址吗

https://www.imooc.com/learn/630https://www.imooc.com/learn/630

**Comment by mountain-shui** [comment]
感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月26日(周四) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [techa03/goodsKill] 可以给下慕课的地址吗 (Issue #156)




  
可以给下慕课的地址吗
  
https://www.imooc.com/learn/630https://www.imooc.com/learn/630
