### ISSUE TITLE
http://www.goodskill.com:8080/goodskill/web/login

### ISSUE THREAD

**Issue by adtfan** [techa03/goodsKill#158]
{"timestamp":1653650764805,"status":404,"error":"Not Found","path":"/goodskill/web/login"}
会是哪里出了问题呢

**Comment by techa03** [comment]
请参考README文档 常见问题 部分

**Comment by techa03** [comment]
#108 @adtfan 可以参考这个

**Comment by techa03** [comment]
#108

**Comment by adtfan** [comment]
3qu



在 2022-05-27 20:02:48，"zheng" ***@***.***> 写道：

#108
