### ISSUE TITLE
快速开始启动SampleWebJspApplication失败

### ISSUE THREAD

**Issue by Jump2nj** [techa03/goodsKill#172]
拉的master分支代码，启动web服务报错同时gooskill服务也报错，Caused by: java.lang.NoSuchMethodError: 'org.apache.dubbo.rpc.RpcContext org.apache.dubbo.rpc.RpcContext.getServerContext()'，看错误信息应该是seata里没有这个方法

**Comment by Jump2nj** [comment]
> 我本地最新master代码单独起的SampleWebJspApplication能启动的，可能是你那边maven依赖没有更新

单独起SampleWebJspApplication是没问题的，但是按照
![image](https://github.com/techa03/goodsKill/assets/24237709/1d98c992-b625-4de2-8ad3-7a415870cc6c)
这个顺序起服务就会出现上面的错误。你试试起完SampleWebJspApplication服务后继续起GoodsKillServiceApplication服务

**Comment by Jump2nj** [comment]
> 我本地最新master代码单独起的SampleWebJspApplication能启动的，可能是你那边maven依赖没有更新

dubbo3.0.13 和seata 1.5.4版本不兼容

**Comment by techa03** [comment]
其实跟启动顺序没什么关系，dubbo降级到3.0.8不报错了，可以试试

> > 我本地最新master代码单独起的SampleWebJspApplication能启动的，可能是你那边maven依赖没有更新
> 
> dubbo3.0.13 和seata 1.5.4版本不兼容

**Comment by Jump2nj** [comment]
good
