### ISSUE TITLE
No SecurityManager accessible to the calling code？找不到SecurityUtils这个类，是Shiro过滤器的启动顺序问题吗？

### ISSUE THREAD

**Issue by tom155680** [techa03/goodsKill#179]
博主您好，我看到您提到由于Shiro兼容性问题以及个人精力有限已移除前端JSP页面、登录注册以及后台管理功能。我在启动Web服务访问login登录页面时出现错误：No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.查阅相关资料后还是未能解决，请问这个是您所提到的兼容性问题吗？还是说我在某些地方没有配置好环境所导致的错误，百思不得其解。如果您有时间的话，能否给予我一个回复，万分感激不尽。
最后想咨询一下博主，可否为该项目建一个交流讨论群呢? 我认为这个项目非常具有学习价值，一定会有很多小伙伴加入！

**Comment by techa03** [comment]
由于升级到springboot3.0后 shiro已经不能使用了，如果非要使用的话可以等shiro的最新版本，目前据我所知是无法兼容的，如果需要登录可以使用老版本tag https://github.com/techa03/goodsKill/tree/v2.7.4。
另外感谢你对项目的认可，交流群的话由于是个人项目也没有太多精力交流，有问题的话可以直接提issue或者查看常见问题解答。
