### ISSUE TITLE
启动不了诶

### ISSUE THREAD

**Issue by lishangpeng** [techa03/goodsKill#45]
![image](https://user-images.githubusercontent.com/26132566/62009898-a69c9080-b196-11e9-8a33-151b2e824b78.png)

**Comment by techa03** [comment]
没启动dubbo服务提供者吧

**Comment by lishangpeng** [comment]
我是先运行GoodsKillRpcServiceSimpleApplication这个的 
![image](https://user-images.githubusercontent.com/26132566/62225392-ee1b5a80-b3ea-11e9-9efa-4ce4d94fb364.png)
这个xml有报错

**Comment by techa03** [comment]
这个红色警告是正常的，数据库密码需要根据个人密码设置进行更改，数据库密码保存在application.yml，可以使用AESUtil工具类进行数据库密码加密替换master.password和slave.password（主从数据库信息可以一致），用你的数据库密码替换运行一下AESUtil里的main方法，默认是root用户
