### ISSUE TITLE
能不能做个开发文档

### ISSUE THREAD

**Issue by Gabriel-18** [techa03/goodsKill#46]
新手看这个有点懵

**Comment by techa03** [comment]
可以考虑的，你是哪些看不懂呢？注释确实少了点，完善中

**Comment by Gabriel-18** [comment]
https://github.com/DuHouAn/MCard


要是能做出类似这种就很完美了
------------------ 原始邮件 ------------------
发件人: "techa03"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 中午11:12
收件人: "techa03/goodsKill"<goodsKill@noreply.github.com>;
抄送: " "<644050173@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [techa03/goodsKill] 能不能做个开发文档 (#46)




可以考虑的，你是哪些看不懂呢？注释确实少了点，完善中
